# Generated by Django 5.1.2 on 2025-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='intent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='tone',
            field=models.CharField(max_length=1000),
        ),
    ]
